from BaseClasses import ItemClassification
from typing import TypedDict, Dict, Set

from BaseClasses import Item

class DR2CItem(Item):
    name: str = "Death Road to Canada"


class ItemDict(TypedDict):
    name: str
    count: int
    classification: ItemClassification


dr2c_items: List[ItemDict] = [
    {'name': "Passport",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Short Trip to Heck Mode",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Long Winding Road Mode",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Deadlier Road Mode",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Familiar EXTREME",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Rare EXTREME",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Marathon Mode",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock KEPA MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Four Jerks EXTREME",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock OPP MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Quick Death MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock INFECTION MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock SEVERE WEATHER MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock RPG MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock Four Jerks SCEPTER",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock MUTATION MODE",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "Unlock INFECTION MODE EXTREME",
     'count': 1,
     'classification': ItemClassification.progression},
    {'name': "10 Zombo Points",
     'count': 1,
     'classification': ItemClassification.useful},
    {'name': "Level Up",
     'count': 1,
     'classification': ItemClassification.useful},
{'name': "Bullets",
     'count': 1,
     'classification': ItemClassification.filler},
{'name': "Shells",
     'count': 1,
     'classification': ItemClassification.filler},
{'name': "Rounds",
     'count': 1,
     'classification': ItemClassification.filler},
{'name': "Medical Supplies",
     'count': 1,
     'classification': ItemClassification.filler},
{'name': "Gasoline",
     'count': 1,
     'classification': ItemClassification.filler},
{'name': "Food",
     'count': 1,
     'classification': ItemClassification.filler},
]